<a href="https://colab.research.google.com/github/VaibhavPundir123/Data-Science-Workshop/blob/main/Data_Science_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello World

In [ ]:
print("Hello World !")

Hello World !


In [ ]:
# Printing My Name
print("Hey! Vaibhav")

Hey! Vaibhav


In [ ]:
## Type is used to define the code whether it is str,bool,int or float
type ("Hello world")

str

In [ ]:
## String Functions
print("Hello World".upper())
print("Hello World".lower())
print("Hello World".title())

HELLO WORLD
hello world
Hello World


In [ ]:
# Count function in a string
"Hello World".count('l')

3

In [ ]:
## Replacing the letters in a string
"Hello World".replace('o','u')

'Hellu Wurld'

#Data Types

Python has several built-in data types to store different kinds of values. Here are some of the most common ones:

*   **Integers (`int`)**: Whole numbers (positive, negative, or zero) without a decimal point.
    *   *Example*: `5`, `-10`, `0`
*   **Floating-point numbers (`float`)**: Numbers with a decimal point.
    *   *Example*: `3.14`, `-0.5`, `10.0`
*   **Strings (`str`)**: Sequences of characters enclosed in single or double quotes.
    *   *Example*: `'Hello'`, `"Python"`
*   **Booleans (`bool`)**: Represents truth values, either `True` or `False`.
    *   *Example*: `True`, `False`
*   **Lists (`list`)**: Ordered, mutable collections of items. Items can be of different data types.
    *   *Example*: `[1, 2, 'apple']`
*   **Tuples (`tuple`)**: Ordered, immutable collections of items. Similar to lists but cannot be changed after creation.
    *   *Example*: `(10, 'banana', 3.14)`
*   **Dictionaries (`dict`)**: Unordered collections of key-value pairs. Keys must be unique and immutable.
    *   *Example*: `{'name': 'Alice', 'age': 30}`
*   **Sets (`set`)**: Unordered collections of unique items.
    *   *Example*: `{1, 2, 3}`

In [ ]:
# Integer
my_integer = 10
print(f"Value: {my_integer}, Type: {type(my_integer)}")

# Float
my_float = 3.14
print(f"Value: {my_float}, Type: {type(my_float)}")

# String
my_string = "Hello, Data Science!"
print(f"Value: '{my_string}', Type: {type(my_string)}")

# Boolean
my_boolean = True
print(f"Value: {my_boolean}, Type: {type(my_boolean)}")

Value: 10, Type: <class 'int'>
Value: 3.14, Type: <class 'float'>
Value: 'Hello, Data Science!', Type: <class 'str'>
Value: True, Type: <class 'bool'>


In [ ]:
# List
my_list = [1, "apple", 3.5]
print(f"Value: {my_list}, Type: {type(my_list)}")

# Tuple
my_tuple = (10, "banana", False)
print(f"Value: {my_tuple}, Type: {type(my_tuple)}")

# Dictionary
my_dictionary = {"name": "Alice", "age": 25}
print(f"Value: {my_dictionary}, Type: {type(my_dictionary)}")

# Set
my_set = {1, 2, 3, 2}
print(f"Value: {my_set}, Type: {type(my_set)}") # Note: Sets only store unique values

Value: [1, 'apple', 3.5], Type: <class 'list'>
Value: (10, 'banana', False), Type: <class 'tuple'>
Value: {'name': 'Alice', 'age': 25}, Type: <class 'dict'>
Value: {1, 2, 3}, Type: <class 'set'>


# Variables

In Python, a **variable** is a named location used to store data in the memory. It's like a container that holds a value. When you create a variable, you assign a value to it, and you can later use that variable name to refer to the value.

Key characteristics of variables in Python:

*   **Assignment**: You assign a value to a variable using the `=` operator.
*   **Dynamic Typing**: You don't need to declare the data type of a variable explicitly. Python automatically infers the data type based on the value you assign.
*   **Reassignment**: You can change the value of a variable at any time.
*   **Naming Conventions**: Variable names must start with a letter or an underscore, and can contain letters, numbers, and underscores. They are case-sensitive.

In [ ]:
# Declaring and assigning variables

# Integer variable
my_age = 30
print(f"My age is: {my_age}")

# String variable
my_name = "Alice"
print(f"My name is: {my_name}")

# Float variable
price = 19.99
print(f"The price is: {price}")

# Boolean variable
is_active = True
print(f"Is active: {is_active}")

# Reassigning a variable
my_age = 31
print(f"My updated age is: {my_age}")

# You can assign the result of an expression to a variable
x = 10
y = 5
sum_result = x + y
print(f"The sum of x and y is: {sum_result}")

My age is: 30
My name is: Alice
The price is: 19.99
Is active: True
My updated age is: 31
The sum of x and y is: 15


## String Concatenation

String concatenation is the operation of joining two or more string values end-to-end to create a new string. In Python, there are several ways to achieve this.

In [ ]:
# Using the '+' operator
# Using " Blank space " So that there is a gap
string1 = "Hello"
string2 = "World"
result_plus = string1 + " " + string2
print(f"Using '+': {result_plus}")

# Concatenating multiple strings
# Using " Blank space " So that there is a gap
string3 = "Python"
string4 = "is"
string5 = "awesome"
result_multiple = string3 + " " + string4 + " " + string5
print(f"Using '+' with multiple strings: {result_multiple}")

Using '+': Hello World
Using '+' with multiple strings: Python is awesome


In [ ]:
# Using f-strings (formatted string literals) - Recommended for readability and efficiency
name = "Alice"
age = 30
message_fstring = f"My name is {name} and I am {age} years old."
print(f"Using f-string: {message_fstring}")

# Another f-string example
fruit = "apple"
color = "red"
description = f"The {fruit} is {color}."
print(f"Using f-string (another example): {description}")

Using f-string: My name is Alice and I am 30 years old.
Using f-string (another example): The apple is red.


In [ ]:
# Using the .join() method (useful for joining a list of strings)
words = ["This", "is", "a", "list", "of", "words"]
joined_string = " ".join(words)
print(f"Using .join(): {joined_string}")

# Joining without a space
characters = ["p", "y", "t", "h", "o", "n"]
joined_characters = "".join(characters)
print(f"Using .join() (no space): {joined_characters}")

Using .join(): This is a list of words
Using .join() (no space): python


## Lists in Python

A **list** in Python is an ordered, mutable (changeable) collection of items. Lists are one of the most versatile and commonly used data types. They can hold items of different data types and are defined by enclosing comma-separated values within square brackets `[]`.

Key characteristics of lists:

*   **Ordered**: Items have a defined order, and that order will not change. New items are typically added to the end.
*   **Changeable (Mutable)**: You can change, add, and remove items after the list has been created.
*   **Allows Duplicates**: Lists can have items with the same value.
*   **Indexed**: Each item in a list has an index, starting from 0 for the first item.

In [ ]:
# Creating a list
my_list = [1, 2, 3, 'hello', True, 3.14]
print(f"Original list: {my_list}")

# Accessing elements by index (0-based indexing)
print(f"First element: {my_list[0]}")
print(f"Fourth element: {my_list[3]}")

# Negative indexing (from the end)
print(f"Last element: {my_list[-1]}")
print(f"Second to last element: {my_list[-2]}")

# Slicing (getting a sub-list)
print(f"Elements from index 1 to 3 (exclusive): {my_list[1:4]}")
print(f"Elements from beginning to index 2 (exclusive): {my_list[:2]}")
print(f"Elements from index 3 to end: {my_list[3:]}")

Original list: [1, 2, 3, 'hello', True, 3.14]
First element: 1
Fourth element: hello
Last element: 3.14
Second to last element: True
Elements from index 1 to 3 (exclusive): [2, 3, 'hello']
Elements from beginning to index 2 (exclusive): [1, 2]
Elements from index 3 to end: ['hello', True, 3.14]


In [ ]:
# Modifying elements
my_list[1] = 'new value'
print(f"List after modifying second element: {my_list}")

# Adding elements
my_list.append('end item') # Adds to the end
print(f"List after appending: {my_list}")

my_list.insert(2, 'inserted item') # Inserts at a specific index
print(f"List after inserting: {my_list}")

# Removing elements
my_list.remove('hello') # Removes the first occurrence of a value
print(f"List after removing 'hello': {my_list}")

popped_item = my_list.pop() # Removes and returns the last item
print(f"List after popping last item: {my_list}, Popped item: {popped_item}")

del my_list[0] # Deletes an item at a specific index
print(f"List after deleting first item: {my_list}")

# Length of a list
print(f"Length of the list: {len(my_list)}")

List after modifying second element: [1, 'new value', 3, 'hello', True, 3.14]
List after appending: [1, 'new value', 3, 'hello', True, 3.14, 'end item']
List after inserting: [1, 'new value', 'inserted item', 3, 'hello', True, 3.14, 'end item']
List after removing 'hello': [1, 'new value', 'inserted item', 3, True, 3.14, 'end item']
List after popping last item: [1, 'new value', 'inserted item', 3, True, 3.14], Popped item: end item
List after deleting first item: ['new value', 'inserted item', 3, True, 3.14]
Length of the list: 5


In [ ]:
# Creating list with a simple example and Printing it
countries = ['United States', 'India', 'China', 'Brazil']
print(countries)

['United States', 'India', 'China', 'Brazil']


In [ ]:
# Indexing
print(countries [0])
print(countries [1])
print(countries [2])
print(countries [3])

United States
India
China
Brazil


In [ ]:
# Adding Countries with a simple method, but it addes in the last option
countries.append('cananda')

In [ ]:
countries


['United States', 'India', 'China', 'Brazil', 'cananda']

In [ ]:
# Adding countries in a certain position
countries.insert(0,'Russia')

In [ ]:
countries

['Russia', 'United States', 'India', 'China', 'Brazil', 'cananda']

In [ ]:
countries_2 = ['UK','Germany','Austria']

In [ ]:
countries + countries_2

['Russia',
 'United States',
 'India',
 'China',
 'Brazil',
 'cananda',
 'UK',
 'Germany',
 'Austria']

In [ ]:
# Nested List
Nested_list = [countries,countries_2]

In [ ]:
Nested_list

[['Russia', 'United States', 'India', 'China', 'Brazil', 'cananda'],
 ['UK', 'Germany', 'Austria']]

In [ ]:
# Removing Elements
countries.remove('United States')

In [ ]:
countries

['Russia', 'India', 'China', 'Brazil', 'cananda']

In [ ]:
#POP Function using the index method
countries.pop(-1)

'cananda'

In [ ]:
countries

['Russia', 'India', 'China', 'Brazil']

In [ ]:
# delete function
del countries [0]

In [ ]:
countries

['India', 'China', 'Brazil']

## Sorting Lists in Python

There are two main ways to sort lists in Python:

1.  **`list.sort()` method**: This method sorts the list **in-place**, meaning it modifies the original list and doesn't return a new one. It returns `None`.
2.  **`sorted()` function**: This built-in function returns a **new sorted list**, leaving the original list unchanged. It can be used on any iterable, not just lists.

In [ ]:
# Example 1: Using the .sort() method (sorts in-place)

my_numbers = [3, 1, 4, 1, 5, 9, 2, 6]
print(f"Original list (before sort): {my_numbers}")

my_numbers.sort()
print(f"List after my_numbers.sort(): {my_numbers}")

# Sorting in reverse order
my_numbers.sort(reverse=True)
print(f"List after my_numbers.sort(reverse=True): {my_numbers}")

my_strings = ["banana", "apple", "date", "cherry"]
print(f"Original string list (before sort): {my_strings}")
my_strings.sort()
print(f"String list after my_strings.sort(): {my_strings}")

Original list (before sort): [3, 1, 4, 1, 5, 9, 2, 6]
List after my_numbers.sort(): [1, 1, 2, 3, 4, 5, 6, 9]
List after my_numbers.sort(reverse=True): [9, 6, 5, 4, 3, 2, 1, 1]
Original string list (before sort): ['banana', 'apple', 'date', 'cherry']
String list after my_strings.sort(): ['apple', 'banana', 'cherry', 'date']


In [ ]:
# Example 2: Using the sorted() function (returns a new list)

my_other_numbers = [3, 1, 4, 1, 5, 9, 2, 6]
print(f"Original list (my_other_numbers): {my_other_numbers}")

sorted_numbers = sorted(my_other_numbers)
print(f"New sorted list (sorted_numbers): {sorted_numbers}")
print(f"Original list remains unchanged (my_other_numbers): {my_other_numbers}")

# Sorting in reverse order with sorted()
reverse_sorted_numbers = sorted(my_other_numbers, reverse=True)
print(f"New reverse sorted list: {reverse_sorted_numbers}")

my_other_strings = ["banana", "apple", "date", "cherry"]
sorted_strings = sorted(my_other_strings)
print(f"New sorted string list: {sorted_strings}")

Original list (my_other_numbers): [3, 1, 4, 1, 5, 9, 2, 6]
New sorted list (sorted_numbers): [1, 1, 2, 3, 4, 5, 6, 9]
Original list remains unchanged (my_other_numbers): [3, 1, 4, 1, 5, 9, 2, 6]
New reverse sorted list: [9, 6, 5, 4, 3, 2, 1, 1]
New sorted string list: ['apple', 'banana', 'cherry', 'date']


In [ ]:
# Sorting a lsit with simple example
numbers = [5, 2, 8, 1, 9]

In [ ]:
numbers.sort()

In [ ]:
numbers

[1, 2, 5, 8, 9]

In [ ]:
numbers.sort(reverse= True)

In [ ]:
numbers


[9, 8, 5, 2, 1]

## Copying Lists in Python

When you copy a list in Python, it's crucial to understand the difference between a **shallow copy** and a **deep copy**.

### Shallow Copy
A shallow copy creates a new list, but it populates the new list with references to the same objects found in the original list. This means if the original list contains mutable objects (like other lists), changing those objects in either the original or the copy will affect both.

Common ways to perform a shallow copy:
*   Slicing: `new_list = original_list[:]`
*   Using the `list()` constructor: `new_list = list(original_list)`
*   Using the `copy()` method (available for lists): `new_list = original_list.copy()`

### Deep Copy
A deep copy creates a new list and recursively copies *all* objects found in the original list. This means that changes to mutable objects within the original list will *not* affect the deep copy, and vice-versa. To perform a deep copy, you typically use the `deepcopy()` function from the `copy` module.

In [ ]:
# Original list
original_list = [1, 2, 3]
print(f"Original list: {original_list}")

# --- Shallow Copy using slicing ---
shallow_copy_slice = original_list[:]
print(f"Shallow copy (slice): {shallow_copy_slice}")

# Modify the shallow copy
shallow_copy_slice.append(4)
print(f"Original list after modifying slice copy: {original_list}")
print(f"Shallow copy (slice) after modification: {shallow_copy_slice}")

# --- Shallow Copy using list() constructor ---
shallow_copy_constructor = list(original_list)
print(f"Shallow copy (constructor): {shallow_copy_constructor}")

# --- Shallow Copy using .copy() method ---
original_list_2 = ['a', 'b', 'c']
shallow_copy_method = original_list_2.copy()
print(f"Shallow copy (.copy() method): {shallow_copy_method}")

Original list: [1, 2, 3]
Shallow copy (slice): [1, 2, 3]
Original list after modifying slice copy: [1, 2, 3]
Shallow copy (slice) after modification: [1, 2, 3, 4]
Shallow copy (constructor): [1, 2, 3]
Shallow copy (.copy() method): ['a', 'b', 'c']


In [ ]:
# Original list with a nested list
original_nested_list = [1, 2, [3, 4]]
print(f"Original nested list: {original_nested_list}")

# Create a shallow copy
shallow_copy_nested = original_nested_list[:]
print(f"Shallow copy of nested list: {shallow_copy_nested}")

# Modify an element in the *outer* list of the shallow copy
shallow_copy_nested.append(5)
print(f"Original nested list after outer modification of shallow copy: {original_nested_list}")
print(f"Shallow copy after outer modification: {shallow_copy_nested}")

# Now, modify an element *inside* the nested list of the shallow copy
# This change will affect both lists because they share the reference to the inner list!
shallow_copy_nested[2].append(99)
print(f"Original nested list after inner modification of shallow copy: {original_nested_list}")
print(f"Shallow copy after inner modification: {shallow_copy_nested}")

Original nested list: [1, 2, [3, 4]]
Shallow copy of nested list: [1, 2, [3, 4]]
Original nested list after outer modification of shallow copy: [1, 2, [3, 4]]
Shallow copy after outer modification: [1, 2, [3, 4], 5]
Original nested list after inner modification of shallow copy: [1, 2, [3, 4, 99]]
Shallow copy after inner modification: [1, 2, [3, 4, 99], 5]


### The critical difference: Shallow copy with nested lists

### Deep Copy for complete independence

In [ ]:
import copy

# Original list with a nested list
original_deep_list = [1, 2, [3, 4]]
print(f"Original list for deep copy: {original_deep_list}")

# Create a deep copy
deep_copy = copy.deepcopy(original_deep_list)
print(f"Deep copy: {deep_copy}")

# Modify an element *inside* the nested list of the deep copy
deep_copy[2].append(99)
print(f"Original list after inner modification of deep copy: {original_deep_list}")
print(f"Deep copy after inner modification: {deep_copy}")

# As you can see, the original list remained unchanged!

Original list for deep copy: [1, 2, [3, 4]]
Deep copy: [1, 2, [3, 4]]
Original list after inner modification of deep copy: [1, 2, [3, 4]]
Deep copy after inner modification: [1, 2, [3, 4, 99]]


## Dictionaries in Python

A **dictionary** in Python is an unordered collection of data values, used to store data values like a map, which, unlike other Data Types that hold only a single value as an element, holds **key:value** pairs. Key-value pairs are separated by a colon (`:`), and each pair is separated by a comma. Dictionaries are enclosed in curly braces `{}`.

Key characteristics of dictionaries:

*   **Unordered** (in Python 3.7+ they maintain insertion order, but historically they were unordered).
*   **Changeable (Mutable)**: You can change, add, and remove items after the dictionary has been created.
*   **No Duplicates Keys**: Duplicate keys are not allowed; if you assign a value to an existing key, the old value will be overwritten.
*   **Keys are Immutable**: Dictionary keys must be of an immutable type (e.g., strings, numbers, tuples). Values can be of any data type.

In [ ]:
# Creating a dictionary
my_dict = {
    "name": "Alice",
    "age": 30,
    "city": "New York",
    "is_student": False
}
print(f"Original dictionary: {my_dict}")

# Accessing values by key
print(f"Name: {my_dict['name']}")
print(f"Age: {my_dict['age']}")

# Getting all keys
print(f"Keys: {my_dict.keys()}")

# Getting all values
print(f"Values: {my_dict.values()}")

# Getting all items (key-value pairs)
print(f"Items: {my_dict.items()}")

Original dictionary: {'name': 'Alice', 'age': 30, 'city': 'New York', 'is_student': False}
Name: Alice
Age: 30
Keys: dict_keys(['name', 'age', 'city', 'is_student'])
Values: dict_values(['Alice', 30, 'New York', False])
Items: dict_items([('name', 'Alice'), ('age', 30), ('city', 'New York'), ('is_student', False)])


In [ ]:
# Modifying values
my_dict['age'] = 31
print(f"Dictionary after modifying age: {my_dict}")

# Adding new key-value pairs
my_dict['occupation'] = "Engineer"
print(f"Dictionary after adding occupation: {my_dict}")

# Removing a key-value pair
del my_dict['city']
print(f"Dictionary after deleting city: {my_dict}")

# Using pop() to remove and get a value
removed_occupation = my_dict.pop('occupation')
print(f"Dictionary after popping occupation: {my_dict}, Removed: {removed_occupation}")

# Checking if a key exists
print(f"Does 'name' exist in dict? {'name' in my_dict}")
print(f"Does 'city' exist in dict? {'city' in my_dict}")

# Length of a dictionary
print(f"Length of the dictionary: {len(my_dict)}")

Dictionary after modifying age: {'name': 'Alice', 'age': 31, 'city': 'New York', 'is_student': False}
Dictionary after adding occupation: {'name': 'Alice', 'age': 31, 'city': 'New York', 'is_student': False, 'occupation': 'Engineer'}
Dictionary after deleting city: {'name': 'Alice', 'age': 31, 'is_student': False, 'occupation': 'Engineer'}
Dictionary after popping occupation: {'name': 'Alice', 'age': 31, 'is_student': False}, Removed: Engineer
Does 'name' exist in dict? True
Does 'city' exist in dict? False
Length of the dictionary: 3


In [ ]:
# Creating a dictionary with mixed data types as values
mixed_dict = {
    "item": "Laptop",
    "price": 1200.50,
    "features": ["16GB RAM", "512GB SSD"],
    "available": True
}
print(f"Mixed dictionary: {mixed_dict}")

# Nested dictionary (dictionary containing another dictionary)
users = {
    "user1": {"name": "Bob", "email": "bob@example.com"},
    "user2": {"name": "Carol", "email": "carol@example.com"}
}
print(f"Nested dictionary (user1's name): {users['user1']['name']}")

Mixed dictionary: {'item': 'Laptop', 'price': 1200.5, 'features': ['16GB RAM', '512GB SSD'], 'available': True}
Nested dictionary (user1's name): Bob


## Conditional Statements: `if`, `elif`, `else`

Conditional statements allow your program to make decisions and execute different blocks of code based on whether certain conditions are `True` or `False`. The primary conditional statements in Python are `if`, `elif` (short for 'else if'), and `else`.

### `if` Statement
The `if` statement is the most basic conditional statement. The code block following `if` executes only if the condition is `True`.

```python
if condition:
    # code to execute if condition is True
```

### `else` Statement
The `else` statement is used in conjunction with an `if` statement to provide an alternative block of code to execute if the `if` condition is `False`.

```python
if condition:
    # code to execute if condition is True
else:
    # code to execute if condition is False
```

### `elif` Statement
The `elif` statement allows you to check multiple conditions sequentially. If the `if` condition is `False`, Python checks the `elif` condition. You can have multiple `elif` blocks. If an `elif` condition is `True`, its corresponding code block executes, and the rest of the `elif` and `else` blocks are skipped.

```python
if condition1:
    # code to execute if condition1 is True
elif condition2:
    # code to execute if condition1 is False and condition2 is True
else:
    # code to execute if all conditions (condition1, condition2) are False
```

In [ ]:
# Example 1: Simple 'if' statement
age = 20

if age >= 18:
    print("You are old enough to vote.")

print("---------------------------------")

# Example 2: 'if-else' statement
temperature = 25

if temperature > 30:
    print("It's a hot day!")
else:
    print("It's not too hot.")

print("---------------------------------")

# Example 3: 'if-elif-else' statement
score = 75

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
else:
    print("Grade: F")

print("---------------------------------")

# Example 4: Multiple 'elif' conditions
hour = 14

if hour < 12:
    print("Good morning!")
elif hour < 18:
    print("Good afternoon!")
elif hour < 22:
    print("Good evening!")
else:
    print("Good night!")

You are old enough to vote.
---------------------------------
It's not too hot.
---------------------------------
Grade: C
---------------------------------
Good afternoon!


In [ ]:
# Simple if else condition
age = 18
if age>= 10:
  print("you are old enough to play football")
else:
  print("you are not old enough to play")

you are old enough to play football


In [ ]:
# Simple elif condtion
age=int(input("enter your age"))

if age>=30:
  print("you are old enough to marry")
  print("you are also old enough to buy a house")
  print("you are also old enough to have children")
elif age<=25:
  print("you should Join a Good College")
  print("you are also old enough to drive a car")
elif age>=20:
  print("you should finish your school")
  print("And needs to get admission in a college")

else:
  print("you should stay with your parent")
  print('and need to focus on your studies')

enter your age7
you should Join a Good College
you are also old enough to drive a car


In [ ]:

age = int(input("Enter your age: "))

if age >= 30:
    print("You are old enough to marry")
    print("You are also old enough to buy a house")
    print("You are also old enough to have children")

elif 25 < age < 30:
    print("You should join a good college")
    print("You are also old enough to drive a car")

elif 20 <= age <= 25:
    print("You should finish your school")
    print("And you need to get admission in a college")

else:
    print("You should stay with your parents")
    print("And need to focus on your studies")


Enter your age: 8
You should stay with your parents
And need to focus on your studies


## Loops in Python: `for` and `while`

Loops are control flow statements that allow you to execute a block of code repeatedly. This is incredibly useful for iterating over collections of items, performing tasks a specific number of times, or continuing an action until a certain condition is met.

### The `for` Loop
`for` loops are used for iterating over a sequence (that is, a list, tuple, dictionary, set, or string) or other iterable objects. The loop executes a block of code for each item in the sequence.

```python
for item in sequence:
    # code to execute for each item
```

### The `while` Loop
`while` loops are used to execute a block of code repeatedly as long as a certain condition is `True`. The condition is checked at the beginning of each iteration.

```python
while condition:
    # code to execute as long as the condition is True
```

In [ ]:
# --- 'for' Loop Examples ---

# Example 1: Iterating over a list
fruits = ["apple", "banana", "cherry"]
print("Iterating over fruits:")
for fruit in fruits:
    print(fruit)

print("\n---------------------------------")

# Example 2: Iterating over a string
word = "Python"
print("Iterating over a word:")
for char in word:
    print(char)

print("\n---------------------------------")

# Example 3: Iterating with range()
# range(5) generates numbers from 0 up to (but not including) 5
print("Counting with range(5):")
for i in range(5):
    print(i)

print("\n---------------------------------")

# Example 4: Iterating with range(start, stop)
print("Counting from 2 to 4 with range(2, 5):")
for i in range(2, 5):
    print(i)

print("\n---------------------------------")

# Example 5: Iterating over a dictionary (keys)
my_dict = {'name': 'Alice', 'age': 30}
print("Iterating over dictionary keys:")
for key in my_dict:
    print(key)

print("\n---------------------------------")

# Example 6: Iterating over dictionary items (key-value pairs)
print("Iterating over dictionary items:")
for key, value in my_dict.items():
    print(f"{key}: {value}")

Iterating over fruits:
apple
banana
cherry

---------------------------------
Iterating over a word:
P
y
t
h
o
n

---------------------------------
Counting with range(5):
0
1
2
3
4

---------------------------------
Counting from 2 to 4 with range(2, 5):
2
3
4

---------------------------------
Iterating over dictionary keys:
name
age

---------------------------------
Iterating over dictionary items:
name: Alice
age: 30


In [ ]:
# --- 'while' Loop Examples ---

# Example 1: Simple while loop
count = 0
print("Counting with a while loop (up to 3):")
while count < 3:
    print(count)
    count += 1 # Increment count to eventually make the condition False

print("\n---------------------------------")

# Example 2: While loop with a break statement
secret_number = 7
guess = 0
print("Guessing game with a while loop and break:")
while True:
    guess = int(input("Guess the secret number (0-9): "))
    if guess == secret_number:
        print("Congratulations! You guessed it.")
        break # Exit the loop
    else:
        print("Try again!")

print("\n---------------------------------")

# Example 3: While loop with a continue statement
# Prints only odd numbers up to 10
num = 0
print("Printing odd numbers with a while loop and continue:")
while num < 10:
    num += 1
    if num % 2 == 0: # If number is even, skip to next iteration
        continue
    print(num)

Counting with a while loop (up to 3):
0
1
2

---------------------------------
Guessing game with a while loop and break:
Guess the secret number (0-9): 7
Congratulations! You guessed it.

---------------------------------
Printing odd numbers with a while loop and continue:
1
3
5
7
9


## Functions in Python

A **function** is a block of organized, reusable code that is used to perform a single, related action. Functions provide better modularity for your application and a high degree of code reusing.

### Why use functions?
*   **Reusability**: Define code once, use it multiple times.
*   **Modularity**: Break down complex problems into smaller, manageable pieces.
*   **Readability**: Makes code easier to understand and maintain.
*   **Abstraction**: Hide the implementation details from the user of the function.

### Defining a Function
In Python, you define a function using the `def` keyword, followed by the function name, parentheses `()`, and a colon `:`. Any input parameters or arguments should be placed within these parentheses.

```python
def function_name(parameters):
    """Docstring: Explain what the function does."""
    # function body
    return result # Optional: return a value
```

### Calling a Function
To execute the code inside a function, you simply 'call' it by its name, followed by parentheses containing any required arguments.

In [ ]:
# Example 1: A simple function without parameters or return value
def greet():
    print("Hello, World!")

# Calling the function
greet()

print("---------------------------------")

# Example 2: Function with a parameter
def greet_name(name):
    print(f"Hello, {name}!")

# Calling the function with an argument
greet_name("Alice")
greet_name("Bob")

print("---------------------------------")

# Example 3: Function with parameters and a return value
def add_numbers(a, b):
    sum_result = a + b
    return sum_result

# Calling the function and storing the result
result = add_numbers(5, 3)
print(f"The sum is: {result}")
print(f"Another sum: {add_numbers(10, 20)}")

print("---------------------------------")

# Example 4: Function with default parameters
def calculate_power(base, exponent=2):
    return base ** exponent

print(f"5 squared (default exponent): {calculate_power(5)}")
print(f"2 to the power of 3: {calculate_power(2, 3)}")

print("---------------------------------")

# Example 5: Function returning multiple values (as a tuple)
def get_name_parts(full_name):
    parts = full_name.split(' ')
    first = parts[0]
    last = parts[-1]
    return first, last

first_name, last_name = get_name_parts("John Doe")
print(f"First Name: {first_name}, Last Name: {last_name}")

Hello, World!
---------------------------------
Hello, Alice!
Hello, Bob!
---------------------------------
The sum is: 8
Another sum: 30
---------------------------------
5 squared (default exponent): 25
2 to the power of 3: 8
---------------------------------
First Name: John, Last Name: Doe


## Built-in Functions in Python

Python provides many functions that are built into the interpreter and are always available for use. These functions streamline common programming tasks and improve code readability.

Some commonly used built-in functions include:

*   `print()`: Outputs objects to the console.
*   `len()`: Returns the length (the number of items) of an object.
*   `type()`: Returns the type of an object.
*   `int()`, `float()`, `str()`, `bool()`: Convert values to integer, float, string, or boolean types, respectively.
*   `input()`: Allows the program to take user input.
*   `sum()`: Sums the items of an iterable.
*   `max()`, `min()`: Returns the largest/smallest item in an iterable or between two or more arguments.
*   `abs()`: Returns the absolute value of a number.
*   `round()`: Rounds a number to a specified number of decimal places.
*   `range()`: Generates a sequence of numbers (often used with `for` loops).
*   `dir()`: Returns a list of the names in the current scope or attributes of an object.
*   `help()`: Invokes the built-in help system.
*   `sorted()`: Returns a new sorted list from the items in an iterable.

In [ ]:
# Example: print() - Output to the console
print("Hello from a built-in function!")

# Example: len() - Get the length of an object
my_list = [10, 20, 30, 40, 50]
print(f"Length of my_list: {len(my_list)}")
my_string = "Python"
print(f"Length of my_string: {len(my_string)}")

# Example: type() - Get the type of an object
print(f"Type of my_list: {type(my_list)}")
print(f"Type of my_string: {type(my_string)}")

# Example: int(), float(), str(), bool() - Type conversion
num_str = "123"
num_int = int(num_str)
print(f"Converted to int: {num_int}, Type: {type(num_int)}")

float_num = float(num_int)
print(f"Converted to float: {float_num}, Type: {type(float_num)}")

boolean_val = bool(0) # 0 is False, any non-zero number is True
print(f"Converted to bool: {boolean_val}, Type: {type(boolean_val)}")

# Example: sum() - Sum of iterable items
numbers = [1, 2, 3, 4, 5]
print(f"Sum of numbers: {sum(numbers)}")

# Example: max() and min() - Max and min values
print(f"Maximum number: {max(numbers)}")
print(f"Minimum number: {min(numbers)}")

# Example: abs() - Absolute value
negative_num = -15
print(f"Absolute value of {negative_num}: {abs(negative_num)}")

# Example: round() - Round a number
pi_value = 3.14159
print(f"Rounded pi to 2 decimal places: {round(pi_value, 2)}")

# Example: range() - Generate a sequence (used in for loop)
print("Numbers from range(3):")
for i in range(3):
    print(i)

# Example: sorted() - Returns a new sorted list
unsorted_list = [5, 1, 4, 2, 8]
print(f"Original list: {unsorted_list}")
print(f"Sorted list (new): {sorted(unsorted_list)}")

Hello from a built-in function!
Length of my_list: 5
Length of my_string: 6
Type of my_list: <class 'list'>
Type of my_string: <class 'str'>
Converted to int: 123, Type: <class 'int'>
Converted to float: 123.0, Type: <class 'float'>
Converted to bool: False, Type: <class 'bool'>
Sum of numbers: 15
Maximum number: 5
Minimum number: 1
Absolute value of -15: 15
Rounded pi to 2 decimal places: 3.14
Numbers from range(3):
0
1
2
Original list: [5, 1, 4, 2, 8]
Sorted list (new): [1, 2, 4, 5, 8]


## Pandas Terminology Comparison with Excel

For those familiar with Excel, understanding Pandas can be easier by drawing parallels between their core concepts. Here's a comparison of common terminology:

| Excel Terminology           | Pandas Terminology                | Description                                                                     |
| :-------------------------- | :-------------------------------- | :------------------------------------------------------------------------------ |
| **Worksheet/Sheet**         | **DataFrame**                     | A 2-dimensional labeled data structure with columns of potentially different types. You can think of it as a spreadsheet or SQL table. |
| **Column**                  | **Series** / **Column**           | A one-dimensional labeled array capable of holding any data type. A DataFrame is a collection of Series (columns). |
| **Row**                     | **Row** / **Index**               | A single record or entry in the DataFrame. Rows are identified by their index (label). |
| **Cell**                    | **Element** / **Value**           | A single data point at the intersection of a row and a column.                   |
| **Headers**                 | **Column Names**                  | The labels for each column in your DataFrame.                                   |
| **Row Numbers**             | **Index** / **Row Labels**        | The labels for each row, often automatically generated (0, 1, 2...) or custom.   |
| **Filtering**               | **Filtering** / **Boolean Indexing** | Selecting rows or columns based on certain criteria or conditions.                 |
| **Sorting**                 | **Sorting** (`sort_values()`, `sort_index()`) | Arranging data in ascending or descending order based on column values or index. |
| **Formulas (e.g., SUM, AVERAGE)** | **Functions** / **Operations**    | Applying mathematical or statistical operations to data (e.g., `sum()`, `mean()`, `apply()`). |
| **Pivot Table**             | **`pivot_table()`**               | Summarizing and reorganizing data, often for aggregation.                       |
| **VLOOKUP/HLOOKUP**         | **`merge()`** / **`join()`**      | Combining data from different DataFrames based on common columns.               |
| **Group By**                | **`groupby()`**                   | Grouping rows based on one or more columns and then applying an aggregation or transformation. |
| **Data Validation**         | **Data Cleaning** / **Validation** | Ensuring data quality and consistency (e.g., checking types, ranges).          |
| **Chart/Graph**             | **Visualization** (Matplotlib/Seaborn) | Creating visual representations of data for analysis and presentation.           |

This table should provide a good starting point for relating your Excel knowledge to Pandas!

## NumPy (Numerical Python)

**NumPy** is a powerful open-source library in Python primarily used for numerical operations. The core of NumPy is its **`ndarray`** object, which is an N-dimensional array that can store homogeneous (same type) data. NumPy arrays are much more efficient for storing and manipulating large datasets than standard Python lists.

### Why NumPy?
*   **Performance**: NumPy's operations are implemented in C, making them significantly faster than Python's native list operations for numerical tasks.
*   **Memory Efficiency**: NumPy arrays consume less memory than Python lists for the same data because they store data contiguously and efficiently.
*   **Mathematical Functions**: It provides a vast collection of high-level mathematical functions to operate on these arrays (e.g., linear algebra, Fourier transform, random number capabilities).
*   **Broadcasting**: A powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.

In [ ]:
import numpy as np

# --- Creating NumPy Arrays ---

# 1. From a Python List
my_list = [1, 2, 3, 4, 5]
numpy_array_from_list = np.array(my_list)
print("1D Array from list:", numpy_array_from_list)
print("Type:", type(numpy_array_from_list))
print("Shape:", numpy_array_from_list.shape)
print("Data Type:", numpy_array_from_list.dtype)

print("\n---------------------------------")

# 2. From nested Python Lists (2D Array / Matrix)
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_matrix = np.array(matrix)
print("2D Array (Matrix) from nested list:\n", numpy_matrix)
print("Shape:", numpy_matrix.shape)

print("\n---------------------------------")

# 3. Using built-in NumPy functions
# Array of zeros
zeros_array = np.zeros((3, 4)) # 3 rows, 4 columns
print("Array of zeros (3x4):\n", zeros_array)

# Array of ones
ones_array = np.ones((2, 2)) # 2 rows, 2 columns
print("\nArray of ones (2x2):\n", ones_array)

# Array with a range of numbers
range_array = np.arange(0, 10, 2) # Start, Stop (exclusive), Step
print("\nArray with range (0-9, step 2):", range_array)

# Linearly spaced numbers
linspace_array = np.linspace(0, 10, 5) # Start, Stop (inclusive), Number of elements
print("\nLinearly spaced array (0-10, 5 elements):", linspace_array)

# Identity matrix
identity_matrix = np.eye(3)
print("\nIdentity matrix (3x3):\n", identity_matrix)

# Random numbers
random_array = np.random.rand(2, 3) # 2 rows, 3 columns of random floats between 0 and 1
print("\nRandom array (2x3):\n", random_array)

1D Array from list: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Data Type: int64

---------------------------------
2D Array (Matrix) from nested list:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

---------------------------------
Array of zeros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of ones (2x2):
 [[1. 1.]
 [1. 1.]]

Array with range (0-9, step 2): [0 2 4 6 8]

Linearly spaced array (0-10, 5 elements): [ 0.   2.5  5.   7.5 10. ]

Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array (2x3):
 [[0.16935599 0.3708087  0.29172637]
 [0.75897105 0.8699839  0.72971074]]


In [ ]:
# --- Basic Array Operations ---

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

# Element-wise addition
addition = arr1 + arr2
print(f"Addition ({arr1} + {arr2}): {addition}")

# Element-wise multiplication
multiplication = arr1 * arr2
print(f"Multiplication ({arr1} * {arr2}): {multiplication}")

# Scalar operations
scalar_mult = arr1 * 5
print(f"Scalar Multiplication ({arr1} * 5): {scalar_mult}")

# Universal Functions (ufuncs)
sqrt_arr1 = np.sqrt(arr1)
print(f"Square root of {arr1}: {sqrt_arr1}")

# Aggregation functions
sum_arr1 = np.sum(arr1)
print(f"Sum of {arr1}: {sum_arr1}")

mean_arr1 = np.mean(arr1)
print(f"Mean of {arr1}: {mean_arr1}")

# Dot product (matrix multiplication for 1D arrays)
dot_product = np.dot(arr1, arr2)
print(f"Dot product of {arr1} and {arr2}: {dot_product}")

# --- Indexing and Slicing ---
arr = np.array([10, 20, 30, 40, 50])
print(f"\nOriginal array for indexing/slicing: {arr}")
print(f"Element at index 0: {arr[0]}")
print(f"Elements from index 1 to 3 (exclusive): {arr[1:4]}")

matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\n2D array for indexing/slicing:\n{matrix_2d}")
print(f"Element at row 0, col 1: {matrix_2d[0, 1]}") # Accessing element
print(f"First row: {matrix_2d[0, :]}") # First row
print(f"Second column: {matrix_2d[:, 1]}") # Second column

Addition ([10 20 30] + [1 2 3]): [11 22 33]
Multiplication ([10 20 30] * [1 2 3]): [10 40 90]
Scalar Multiplication ([10 20 30] * 5): [ 50 100 150]
Square root of [10 20 30]: [3.16227766 4.47213595 5.47722558]
Sum of [10 20 30]: 60
Mean of [10 20 30]: 20.0
Dot product of [10 20 30] and [1 2 3]: 140

Original array for indexing/slicing: [10 20 30 40 50]
Element at index 0: 10
Elements from index 1 to 3 (exclusive): [20 30 40]

2D array for indexing/slicing:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, col 1: 2
First row: [1 2 3]
Second column: [2 5 8]


In [ ]:
# Creating an array
data = np.array([[1,4], [2,5], [3,3]])

In [ ]:
data

array([[1, 4],
       [2, 5],
       [3, 3]])

In [ ]:
# Creating a dataframe
import pandas as pd
pd.DataFrame(data)


0  1
0  1  4
1  2  5
2  3  3

In [ ]:
import pandas as pd

# Create a dictionary where keys are column names and values are lists of data
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Score': [85, 92, 78, 95],
    'Grade': ['B', 'A', 'C', 'A']
}

# Create a DataFrame from the dictionary
df_students = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame created from a dictionary:")
print(df_students)

print("\n--- Another example with mixed data types ---\n")

data_mixed = {
    'Product': ['Laptop', 'Mouse', 'Keyboard'],
    'Price': [1200.50, 25.99, 75.00],
    'In_Stock': [True, True, False]
}

df_products = pd.DataFrame(data_mixed)
print("DataFrame with mixed data types:")
print(df_products)

DataFrame created from a dictionary:
   Student  Score Grade
0    Alice     85     B
1      Bob     92     A
2  Charlie     78     C
3    Diana     95     A

--- Another example with mixed data types ---

DataFrame with mixed data types:
    Product    Price  In_Stock
0    Laptop  1200.50      True
1     Mouse    25.99      True
2  Keyboard    75.00     False


In [ ]:
# reading the csv file
import pandas as pd
df_exams = pd.read_csv('StudentsPerformance.csv')

In [ ]:
# show the whole rows in a dataframe
df_exams

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [ ]:
pd.set_option("display.max_rows", 1000)
df_exams

In [ ]:
# show first 5 rows in a dataframe
df_exams.head()

In [ ]:
# show last 5 rows of data
df_exams.tail()

In [ ]:
# Show firt n rows in dataframe
df_exams.head(10)

In [ ]:
# Show last n rows of data
df_exams.tail(10)

In [ ]:
# getting access to the shape attribute meaning rows and coloumns
df_exams.shape

In [ ]:
# Getting access to the index attribute meaning from where the data is starting and finishing and the step is increment
df_exams.index

In [ ]:
# data types of each column
df_exams.columns

In [ ]:
# showing th info of the dataframe
df_exams.info()

In [ ]:
# data types of each column
df_exams.dtypes

In [ ]:
# Describibg basic statistics of the dataframe
df_exams.describe()

# Functions

In [ ]:
# obtaining the length of the dataframe
len(df_exams)

In [ ]:
# obtaining the highest index of the dataframe
max(df_exams.index)

In [ ]:
# obtaining the lowest index of the dataframe
min(df_exams.index)

In [ ]:
# obtaining the data type
type(df_exams)

In [ ]:
# rounding the values of the dataset
round(df_exams, 2)

# Selecting one column

In [ ]:
# selecting a column with [] prefered way to select a column
df_exams['gender']

In [ ]:
# check out the data type of a coloumn
type(df_exams['gender'])

In [ ]:
# series attributes and menthods
df_exams['gender'].index
df_exams['gender'].head()

# Syntax 2

In [ ]:
# select a column with.
df_exams.gender

# Selecting two or more coloumns

In [ ]:
# Select 2 coloumns using [[]]
df_exams[['gender', 'math score']]

In [ ]:
# check out the data type of the selection
type(df_exams[['gender', 'math score']])

In [ ]:
# select 2 or more coloumns
df_exams[['gender', 'math score','reading score','writing score']]


# Adding a New Coloumn in Dataframe

In [ ]:
# adding new coloumn to dataframe with a scalar value
df_exams['language score'] = 70
df_exams

# Adding a new column with an array

In [ ]:
# create an array of 1000 elemnts
language_score = np.arange(0,1000)

In [ ]:
# Length of array
len(np.arange(0,1000))

In [ ]:
# adding a new coloumn to dataframe with an array
df_exams['language score'] = language_score
df_exams

In [ ]:
# create a random integer numbers between 1 and 100
int_language_score = np.random.randint(1,100, size=1000)

In [ ]:
# adding a new coloumn with random array numbers
df_exams['language score'] = int_language_score
df_exams

In [ ]:
# using assign () to add multiple columns
#df_exams = df_exams.assign(new_language_score = language_score)
#df_exams

# Math Operations

In [ ]:
# select a column and calculate total sum
df_exams ['math score'].sum()

np.int64(66089)

In [ ]:
# count, mean, std ,max and min
df_exams['math score'].count()
df_exams['math score'].mean()
df_exams['math score'].std()
df_exams['math score'].max()
df_exams['math score'].min

<bound method Series.min of 0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64>

In [ ]:
# easier calculation with.describe
df_exams.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Operation in Rows

In [ ]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']


0      218
1      247
2      278
3      148
4      229
      ... 
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [ ]:
# calculating the average score and assigning the result to a new column as average and using round function to limit the decimal value
df_exams['average']= (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3
df_exams.round(2)

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  average  
0                      none          72             72             74    72.67  
1                 completed          69             90             88    82.33  
2                      none          90             95             93    92.67  
3                      none          47             57             44    49.33  
4                      none          76             78             75    76.33  
..                      ...         ...            ...            ...      ...  
995               completed          88             99             95    94.00  
996                    none          62             55             55    57.33  
997               completed          59             71             65    65.00  
998               completed          68             78             77    74.33  
999                    none          77             86             86    83.00  

[1000 rows x 9 columns]

# Value Count

In [ ]:
# counting gender elemnts
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [ ]:
# return the relative frequecny ( divide all values by the sum of values)
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [ ]:
# counting parental level ofeducation elements by category
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [ ]:
# return the realtive frequency and round to 2 decimals
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

# Sort a dataframe

In [ ]:
# sort by one column in ascending order
df_exams.sort_values(by='math score')

gender race/ethnicity parental level of education         lunch  \
59   female        group C            some high school  free/reduced   
980  female        group B                 high school  free/reduced   
17   female        group B            some high school  free/reduced   
787  female        group B                some college      standard   
145  female        group C                some college  free/reduced   
..      ...            ...                         ...           ...   
623    male        group A                some college      standard   
625    male        group D                some college      standard   
962  female        group E          associate's degree      standard   
458  female        group E           bachelor's degree      standard   
916    male        group E           bachelor's degree      standard   

    test preparation course  math score  reading score  writing score  \
59                     none           0             17             10   
980                    none           8             24             23   
17                     none          18             32             28   
787                    none          19             38             32   
145                    none          22             39             33   
..                      ...         ...            ...            ...   
623               completed         100             96             86   
625               completed         100             97             99   
962                    none         100            100            100   
458                    none         100            100            100   
916               completed         100            100            100   

        average  
59     9.000000  
980   18.333333  
17    26.000000  
787   29.666667  
145   31.333333  
..          ...  
623   94.000000  
625   98.666667  
962  100.000000  
458  100.000000  
916  100.000000  

[1000 rows x 9 columns]

In [ ]:
# sort descending by one column
df_exams.sort_values(by='math score', ascending=False)

gender race/ethnicity parental level of education         lunch  \
451  female        group E                some college      standard   
458  female        group E           bachelor's degree      standard   
962  female        group E          associate's degree      standard   
149    male        group E          associate's degree  free/reduced   
623    male        group A                some college      standard   
..      ...            ...                         ...           ...   
145  female        group C                some college  free/reduced   
787  female        group B                some college      standard   
17   female        group B            some high school  free/reduced   
980  female        group B                 high school  free/reduced   
59   female        group C            some high school  free/reduced   

    test preparation course  math score  reading score  writing score  \
451                    none         100             92             97   
458                    none         100            100            100   
962                    none         100            100            100   
149               completed         100            100             93   
623               completed         100             96             86   
..                      ...         ...            ...            ...   
145                    none          22             39             33   
787                    none          19             38             32   
17                     none          18             32             28   
980                    none           8             24             23   
59                     none           0             17             10   

        average  
451   96.333333  
458  100.000000  
962  100.000000  
149   97.666667  
623   94.000000  
..          ...  
145   31.333333  
787   29.666667  
17    26.000000  
980   18.333333  
59     9.000000  

[1000 rows x 9 columns]

In [ ]:
# sort descending by multiple column
df_exams.sort_values(by=['math score', 'reading score'], ascending=False)

gender race/ethnicity parental level of education         lunch  \
149    male        group E          associate's degree  free/reduced   
458  female        group E           bachelor's degree      standard   
916    male        group E           bachelor's degree      standard   
962  female        group E          associate's degree      standard   
625    male        group D                some college      standard   
..      ...            ...                         ...           ...   
145  female        group C                some college  free/reduced   
787  female        group B                some college      standard   
17   female        group B            some high school  free/reduced   
980  female        group B                 high school  free/reduced   
59   female        group C            some high school  free/reduced   

    test preparation course  math score  reading score  writing score  \
149               completed         100            100             93   
458                    none         100            100            100   
916               completed         100            100            100   
962                    none         100            100            100   
625               completed         100             97             99   
..                      ...         ...            ...            ...   
145                    none          22             39             33   
787                    none          19             38             32   
17                     none          18             32             28   
980                    none           8             24             23   
59                     none           0             17             10   

        average  
149   97.666667  
458  100.000000  
916  100.000000  
962  100.000000  
625   98.666667  
..          ...  
145   31.333333  
787   29.666667  
17    26.000000  
980   18.333333  
59     9.000000  

[1000 rows x 9 columns]

In [ ]:
# sort decending by multiple columns and update dataframe
df_exams.sort_values(by=['math score', 'reading score'], ascending=False, inplace=True)


In [ ]:
df_exams

gender race/ethnicity parental level of education         lunch  \
149    male        group E          associate's degree  free/reduced   
458  female        group E           bachelor's degree      standard   
916    male        group E           bachelor's degree      standard   
962  female        group E          associate's degree      standard   
625    male        group D                some college      standard   
..      ...            ...                         ...           ...   
145  female        group C                some college  free/reduced   
787  female        group B                some college      standard   
17   female        group B            some high school  free/reduced   
980  female        group B                 high school  free/reduced   
59   female        group C            some high school  free/reduced   

    test preparation course  math score  reading score  writing score  \
149               completed         100            100             93   
458                    none         100            100            100   
916               completed         100            100            100   
962                    none         100            100            100   
625               completed         100             97             99   
..                      ...         ...            ...            ...   
145                    none          22             39             33   
787                    none          19             38             32   
17                     none          18             32             28   
980                    none           8             24             23   
59                     none           0             17             10   

        average  
149   97.666667  
458  100.000000  
916  100.000000  
962  100.000000  
625   98.666667  
..          ...  
145   31.333333  
787   29.666667  
17    26.000000  
980   18.333333  
59     9.000000  

[1000 rows x 9 columns]

In [ ]:
# sort decending with a key function
df_exams.sort_values(by=['race/ethnicity'], ascending=True, key=lambda col: col.str.lower())

gender race/ethnicity parental level of education         lunch  \
741  female        group A          associate's degree  free/reduced   
151    male        group A           bachelor's degree      standard   
811    male        group A                 high school  free/reduced   
112    male        group A          associate's degree      standard   
25     male        group A             master's degree  free/reduced   
..      ...            ...                         ...           ...   
751    male        group E                some college      standard   
915  female        group E                some college      standard   
592    male        group E           bachelor's degree      standard   
479    male        group E          associate's degree      standard   
517  female        group E                some college      standard   

    test preparation course  math score  reading score  writing score  \
741                    none          37             57             56   
151                    none          77             67             68   
811                    none          45             47             49   
112                    none          54             53             47   
25                     none          73             74             72   
..                      ...         ...            ...            ...   
751                    none          68             72             65   
915                    none          68             70             66   
592                    none          68             68             64   
479                    none          76             71             67   
517               completed          66             74             73   

       average  
741  50.000000  
151  70.666667  
811  47.000000  
112  51.333333  
25   73.000000  
..         ...  
751  68.333333  
915  68.000000  
592  66.666667  
479  71.333333  
517  71.000000  

[1000 rows x 9 columns]

# Create Index

In [ ]:
import numpy as np
import random

In [ ]:
# creating non repetitive values for the index
new_index = np.arange(0,1000)

In [ ]:
# shuffling the indexes
random.shuffle(new_index)

In [ ]:
new_index

array([927, 736, 386, 413, 586, 434, 475, 493, 580,  28, 956, 266,  69,
       471, 802, 460, 991, 700, 729, 973, 616, 556,  99, 173, 501, 842,
        65, 424, 581, 229, 820,  94, 406, 232, 284, 815, 970, 587, 624,
       946, 207,   3, 299, 792,  85,  16, 941, 535, 315, 468, 458, 412,
       707, 936, 159,  46, 996, 444, 906, 648, 888,  64, 694, 668, 263,
        36,  53, 644, 403,  76, 500, 130, 964, 561, 876, 326, 567, 681,
       577, 657, 401, 637, 904, 156, 416, 199, 614, 710, 150, 604, 817,
       329, 335, 241,  60, 477, 650, 204, 747, 362, 371,   6, 676, 318,
       572, 234,  66, 293, 218, 426, 787, 296, 531, 818, 124, 328, 683,
       260, 557,  77, 330, 193, 107, 409, 276, 869,  92, 113,  43, 236,
       617, 837, 940, 183, 167, 415, 158,  24, 863, 663,   0, 954, 601,
       356, 725, 594, 220, 696, 591, 929, 405, 898, 659, 823, 250,  52,
       775, 513, 735, 149, 419,  29, 850, 987, 952, 814, 671, 393, 824,
       745, 238, 245, 894, 378, 825,  23, 963,  18,  96,   4, 99

In [ ]:
# create a new column with new index
df_exams['new_index'] = new_index
df_exams

gender race/ethnicity parental level of education         lunch  \
149    male        group E          associate's degree  free/reduced   
458  female        group E           bachelor's degree      standard   
916    male        group E           bachelor's degree      standard   
962  female        group E          associate's degree      standard   
625    male        group D                some college      standard   
..      ...            ...                         ...           ...   
145  female        group C                some college  free/reduced   
787  female        group B                some college      standard   
17   female        group B            some high school  free/reduced   
980  female        group B                 high school  free/reduced   
59   female        group C            some high school  free/reduced   

    test preparation course  math score  reading score  writing score  \
149               completed         100            100             93   
458                    none         100            100            100   
916               completed         100            100            100   
962                    none         100            100            100   
625               completed         100             97             99   
..                      ...         ...            ...            ...   
145                    none          22             39             33   
787                    none          19             38             32   
17                     none          18             32             28   
980                    none           8             24             23   
59                     none           0             17             10   

        average  new_index  
149   97.666667        927  
458  100.000000        736  
916  100.000000        386  
962  100.000000        413  
625   98.666667        586  
..          ...        ...  
145   31.333333        605  
787   29.666667         22  
17    26.000000        246  
980   18.333333        827  
59     9.000000        188  

[1000 rows x 10 columns]

# Set Index

In [ ]:
# set new_index column as index
df_exams.set_index('new_index')


gender race/ethnicity parental level of education         lunch  \
new_index                                                                    
908        female        group D                some college  free/reduced   
242        female        group D                some college      standard   
336        female        group C                 high school  free/reduced   
784          male        group C                 high school  free/reduced   
36         female        group E             master's degree      standard   
...           ...            ...                         ...           ...   
972          male        group C                some college      standard   
123          male        group A          associate's degree  free/reduced   
458        female        group B             master's degree      standard   
15         female        group C                some college      standard   
884        female        group B           bachelor's degree      standard   

          test preparation course  math score  reading score  writing score  \
new_index                                                                     
908                          none          77             86             86   
242                     completed          68             78             77   
336                     completed          59             71             65   
784                          none          62             55             55   
36                      completed          88             99             95   
...                           ...         ...            ...            ...   
972                          none          76             78             75   
123                          none          47             57             44   
458                          none          90             95             93   
15                      completed          69             90             88   
884                          none          72             72             74   

             average  
new_index             
908        83.000000  
242        74.333333  
336        65.000000  
784        57.333333  
36         94.000000  
...              ...  
972        76.333333  
123        49.333333  
458        92.666667  
15         82.333333  
884        72.666667  

[1000 rows x 9 columns]

In [ ]:
# Sort dataframe by new Index
df_exams.sort_index()
df_exams


gender race/ethnicity parental level of education         lunch  \
999  female        group D                some college  free/reduced   
998  female        group D                some college      standard   
997  female        group C                 high school  free/reduced   
996    male        group C                 high school  free/reduced   
995  female        group E             master's degree      standard   
..      ...            ...                         ...           ...   
4      male        group C                some college      standard   
3      male        group A          associate's degree  free/reduced   
2    female        group B             master's degree      standard   
1    female        group C                some college      standard   
0    female        group B           bachelor's degree      standard   

    test preparation course  math score  reading score  writing score  \
999                    none          77             86             86   
998               completed          68             78             77   
997               completed          59             71             65   
996                    none          62             55             55   
995               completed          88             99             95   
..                      ...         ...            ...            ...   
4                      none          76             78             75   
3                      none          47             57             44   
2                      none          90             95             93   
1                 completed          69             90             88   
0                      none          72             72             74   

       average  new_index  
999  83.000000        908  
998  74.333333        242  
997  65.000000        336  
996  57.333333        784  
995  94.000000         36  
..         ...        ...  
4    76.333333        972  
3    49.333333        123  
2    92.666667        458  
1    82.333333         15  
0    72.666667        884  

[1000 rows x 10 columns]

In [ ]:
# sort decending by index
df_exams.sort_index(ascending=False, inplace = True)
df_exams

gender race/ethnicity parental level of education         lunch  \
999  female        group D                some college  free/reduced   
998  female        group D                some college      standard   
997  female        group C                 high school  free/reduced   
996    male        group C                 high school  free/reduced   
995  female        group E             master's degree      standard   
..      ...            ...                         ...           ...   
4      male        group C                some college      standard   
3      male        group A          associate's degree  free/reduced   
2    female        group B             master's degree      standard   
1    female        group C                some college      standard   
0    female        group B           bachelor's degree      standard   

    test preparation course  math score  reading score  writing score  \
999                    none          77             86             86   
998               completed          68             78             77   
997               completed          59             71             65   
996                    none          62             55             55   
995               completed          88             99             95   
..                      ...         ...            ...            ...   
4                      none          76             78             75   
3                      none          47             57             44   
2                      none          90             95             93   
1                 completed          69             90             88   
0                      none          72             72             74   

       average  new_index  
999  83.000000        908  
998  74.333333        242  
997  65.000000        336  
996  57.333333        784  
995  94.000000         36  
..         ...        ...  
4    76.333333        972  
3    49.333333        123  
2    92.666667        458  
1    82.333333         15  
0    72.666667        884  

[1000 rows x 10 columns]

# Rename Column

In [ ]:
# Rename column and overwrite values of dataframe
df_exams.rename(columns={'gender': 'Gender'})

Gender race/ethnicity parental level of education         lunch  \
999  female        group D                some college  free/reduced   
998  female        group D                some college      standard   
997  female        group C                 high school  free/reduced   
996    male        group C                 high school  free/reduced   
995  female        group E             master's degree      standard   
..      ...            ...                         ...           ...   
4      male        group C                some college      standard   
3      male        group A          associate's degree  free/reduced   
2    female        group B             master's degree      standard   
1    female        group C                some college      standard   
0    female        group B           bachelor's degree      standard   

    test preparation course  math score  reading score  writing score  \
999                    none          77             86             86   
998               completed          68             78             77   
997               completed          59             71             65   
996                    none          62             55             55   
995               completed          88             99             95   
..                      ...         ...            ...            ...   
4                      none          76             78             75   
3                      none          47             57             44   
2                      none          90             95             93   
1                 completed          69             90             88   
0                      none          72             72             74   

       average  new_index  
999  83.000000        908  
998  74.333333        242  
997  65.000000        336  
996  57.333333        784  
995  94.000000         36  
..         ...        ...  
4    76.333333        972  
3    49.333333        123  
2    92.666667        458  
1    82.333333         15  
0    72.666667        884  

[1000 rows x 10 columns]

In [ ]:
# rename multiple columns and update the dataframe with inplace argument
df_exams.rename(columns={'math score': 'MS', 'reading score': 'RS', 'writing score': 'WS'}, inplace=True)
df_exams

gender race/ethnicity parental level of education         lunch  \
999  female        group D                some college  free/reduced   
998  female        group D                some college      standard   
997  female        group C                 high school  free/reduced   
996    male        group C                 high school  free/reduced   
995  female        group E             master's degree      standard   
..      ...            ...                         ...           ...   
4      male        group C                some college      standard   
3      male        group A          associate's degree  free/reduced   
2    female        group B             master's degree      standard   
1    female        group C                some college      standard   
0    female        group B           bachelor's degree      standard   

    test preparation course  MS  RS  WS    average  new_index  
999                    none  77  86  86  83.000000        908  
998               completed  68  78  77  74.333333        242  
997               completed  59  71  65  65.000000        336  
996                    none  62  55  55  57.333333        784  
995               completed  88  99  95  94.000000         36  
..                      ...  ..  ..  ..        ...        ...  
4                      none  76  78  75  76.333333        972  
3                      none  47  57  44  49.333333        123  
2                      none  90  95  93  92.666667        458  
1                 completed  69  90  88  82.333333         15  
0                      none  72  72  74  72.666667        884  

[1000 rows x 10 columns]

In [ ]:
# Rename index 0,1 and 2 and update the dataframe
df_exams.rename(index={0: 'A', 1: 'B', 2: 'C'}, inplace=True)

In [ ]:
# Show first 3 rows
df_exams.head(3)

gender race/ethnicity parental level of education         lunch  \
999  female        group D                some college  free/reduced   
998  female        group D                some college      standard   
997  female        group C                 high school  free/reduced   

    test preparation course  MS  RS  WS    average  new_index  
999                    none  77  86  86  83.000000        908  
998               completed  68  78  77  74.333333        242  
997               completed  59  71  65  65.000000        336